CONFIG_ZMK_USB_LOGGING=n
# Enable the RGB LED widget (automatically enabled by the adapter, but good for safety)
CONFIG_RGBLED_WIDGET=y

# Make the Left central board blink for its own battery, then the Right peripheral's battery
CONFIG_RGBLED_WIDGET_BATTERY_SHOW_PERIPHERALS=y

# Blink red on every level change if battery drops below 10%
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
